kind: ConfigMap
apiVersion: v1
metadata:
  name: hello-config
data:
  appsettings.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Warning"
        }
      },
     "AllowedHosts": "*"
    }